package com.mygdx.mongojocs.bravewar;

public class Text {

	public static final String 
		
		connect="conectar",
		abort="abortar partida",		
		soundOnOff[]={"sonido on","sonido off"},
		flagOnOff[]={"bandera autom.","bandera propia"},
		flagEdit="editar bandera",
		nameEdit="editar nombre",
		credits="creditos",
		exit="salir",
		loging="Conectando...",
		waitGameInit="Esperando",
		attack="atacar",
		move="mover unidades",
		buy="adquirir",
		options="opciones",
		chooseRegion="escoge una region",
		cancel="cancelar",
		empty="   ",
		info="detalles",
		talk="enviar un mensaje",
		whatToBuy="que deseas comprar?",
		buyMenu[]={"tropas","comida","combustible"},
		troopType[]={"guerreros","soldados","orcos","tanques"},
		howManyUnits="cuantas unidades?",
		total="Total",
		howManyTroops="cuantas tropas?",
		emptyRegion="region vacia",
		regionType[]={"region pobre","region pobre","region normal","region rica","region muy rica","region excepcional"},
		left="dejar en celda",
		leftShort="quedaran",
		notEnoughPoints[]={"no tienes suficientes puntos"},
		roundConfirm="confirmar turno",
		oppSelect="Elige el objetivo",
		tileSelect="Elige una parcela",
		movement="Movimiento",
		attackfrom="Ataque",
		waitOpponent="Espera...",
		notMoney="Dinero insuficiente",
		battleWon="Ganas la batalla!",
		battleLost="Has sido derrotado",
		reason[]={"no puedes atacar","jugador ocupado","el enemigo huye"},
		retreat="retirarse",
		confirmRetreat="deseas retirarte?",
		opponentRetreated="el enemigo se rinde!",
		need="necesitas:",
		underAttack="Eres atacado!",
		fightOrRetreat="Entras en guerra?",
		chatWindow="Ventana de chat",
		chatSend="Enviar",
		lobbyChatSend="Enviar,",
		inputNameWindow="Nombre del ej�rcito",
		inputNameField="Introduce tu nombre",
		inputNameOk="OK",		
		inputGameNameWindow="Nombre de la partida",
		inputGameNameField="Introduce un nombre",
		inputGameNameOk="Acepta",		
		flagEditHelp="5:pint *:col #:borr",
		bravewar="BraveWar",
		programming="Programacion:",
		david="David Rodriguez",
		pau="Pau Vivancos",
		graphi="Graficos",
		jordi="Jordi Palome",
		music="Sonido",
		jordi2="Jordi Gutierrez",
		microjocs="Microjocs.com 2003",
		winsTheGame="gana!",		
		confirmAbort="seguro de abandonar?",
		press0ToAbort="0:salir  *:chat",
		sendToWho="Mensaje para?",
		everyone="Todos",
		clearFlagConfirm="borrar todo?",
		loginFailed="no se pudo conectar",
		cannotRetreat="no puedes huir",
		bravewarGames="partidas",
		createGame="crear partida",
		newGame="nueva partida",
		goCreate="crear!",
		joinOrBack="0:Atras  5:unirse",		
		acceptOrBack="0:Salir  5:elige",		
		moneyCat[]={"100$","1000$","10000$"},
		troopCat[]={"basicas","medias","maximas"},
		timeCat[]={"5 min","15 min","30 min","45 min","60 min"},
		oppWait="Espera al oponente",
		name="nombre",
		players="jugadores",
		troops="tropas",
		tim="Tiempo",
		money="Dinero",
		joinTo="Unirse a ",
		wait="Espera...",
		campaignOver="la guerra termina",
		timeOver="fin del tiempo",
		scores="puntuaciones",
		pushAnyBut="pulsa cualquier boton",
		survivor="sobrevive",
		regionInWar="region en guerra",
		vs="contra",
		gameStarting="iniciando partida",
		oldVersion[]={"existe una version","mas nueva."},
		tooOldVersion[]={"esta version es","demasiado antigua."},
		confirmReset="abortar partida?",
		
		accSelect="elige",
		accJoin="unirse",
		menBack="salir",
		starChat="*:chat",
		minutesLeft="Minutos restantes: "
		;


}