package com.mygdx.mongojocs.cerberus;

public class Text {

	public static final String 
		menutxt="menu",
		empty="vacio",
		levelname[]={"pantan","cuevas","bosque","castill"},
		leveldesc[]={"pantano cenagoso","cuevas del volcan","bosque oscuro","castillo Rochefort"},
		weaponname[]={"Katana","Latigo","Boomerang"},
		weapontext[][]={{"alcance corto y mortal.","pulsa repetidamente y","encadenaras golpes]"},
				{"de ataque lento pero","muy largo alcance]"," "},
				{"golpea y luego regresa]","pulsa arriba o abajo y se","desviarlo ligeramente]"}},
		unknown="????",
		notavail[]={"aun no posees este","objeto.",""},
		armorname[]={"casco","peto","guanteletes","botas","capa"},
		armortext[][]={{"debilita la gravedad","y te permite saltar","mas alto]"},
			       {"aumenta tu resistencia","haciendo mas duro","tu cuerpo]"},
			       {"cada uno de tus ataques","tiene doble poder de","da@o]"},
			       {"puedes hacer un doble","salto en el aire sin","pisar el suelo]"},
			       {"puedes moverte mientras","caes usando los","botones de direccion]"}},		
		newgame="nuevo juego",
		loadgame="continuar",
		sound_on="sonido si",
		sound_off="sonido no",
		controls="controles",
		credits="acerca de]]]",
		exit="salir",
		weaponselect="escoge un arma",
		gameover="FIN DEL JUEGO",
		loading="cargando",
		getready="preparado_",
		levelcomplete="nivel completado_",
		lifes="vida",
		contin="volver al juego",
		abort="Abortar la partida",
		load="continuar partida",
		save="guardar partida",
		save_instr="5:guardar  0:no guardar",
		load_instr="5:cargar  0:cancelar",
		map="mapa",
		controlstext[]={"4=6: camina izquierda=derecha","2: saltar","8: agacharse","5: ataque","5<agachado>: patada","5<en salto>: ataque en el aire","izq] o der] dos veces: correr"},
		controlsstick="tambien control con stick",
		diedtimes="veces muerto",		
		diedleft=" quedan",
		designed="Dise@ado por",
		david="David Rodriguez",
		coded="Programacion",
		graphic="Graficos",
		elias="Elias Lozano",
		juan="Juan Antonio Gomez",
		jordi="Jordi Gutierrez",
		music="Musica",
		microjocs="microjocs 2003",
		web="www]microjocs]com",
		//thanks="agradecimientos", MONGOFIX
			thanks="gracias por el codigo",
		epilogue[]={"]]]de repente[ cuando","cerberus grito tan","fuerte como un trueno[","el fuego del infierno","ascendio y absorbio","tanto a samuel como","al monstruo hacia las","puertas del infierno]]]","quizas[ahora sea cuando","la batalla empieza"," ","continuara]]]"},
		prologue[][]={
				   {"Se dice que cada 200","a@os[ el emperador del","inframundo[hades[abre","las puertas del infierno","e intenta conquistar el","mundo] hoy[en el a@o 1765[","criaturas malignas han","aparecido alrededor del","castillo rochefort]]]","Samuel coge su espada]","Sabe que ha llegado","su momento]]]"},
				   {"ya no cabe duda]]]esta","vez[el guardian del","infierno[cerberus ha sido","enviado para dominar","nuestro mundo] sus","increibles poderes han","resucitado a las","malvadas criaturas de","los pantanos[bosques y","cuevas] no podras","enfrentarte a cerberus","hasta que los destruyas]]]"},
				   {"desde el principio de","los tiempos[los guerreros","de la luz han combatido","el mal con la legendaria","armadura de la luz]","si la encontaras[","recibirias los enormes","poderes de los angeles[","que seguramente te","asegurarian la fuerza","necesaria para aplastar","los planes de cerberus]]]"},
				   {"la barrera magica ha","caido[ahora puedes por","fin entrar al castillo","y enfrentarte a cerberus[","pero ten cuidado[ahora el","castillo se ha convertido","en una parte del mismo","infierno] sus puertas","se han abierto[no","queda mucho tiempo[[[","","que la luz guie tu","camino]]]"}
				 },		
		congrats="enhorabuena",
		yourrank="esta vez obtienes el ranking",		
		cheatask="quieres la armadura completa?",
		yes="SI",
		no="NO"				
	;

}