package com.mygdx.mongojocs.qblast;

public class QBlastText {

	public static final String 
		pushAnyButton = "pulsa algun boton",
		play = "jugar",
		soundOn = "sonido en on",
		soundOff = "sonido en off",
		vibrOn = "vibra en on",
		vibrOff = "vibra en off",
		controlA = "modo 7650[6600",
		controlB = "modo 3650",
		help = "ayuda",
		about = "acerca de]]]",
		exit = "salir",
		levelComplete = "nivel completado",
		extraSeconds = "segundos extra",
		outOfTime = "se acabo el tiempo",
		gameOver = "fin de juego",
		chooseStartLevel = "escoge nivel inicial",
		level = "nivel",
		resume = "continuar",
		abort = "abortar",		
		butConf[][] = {{"4[6[2[8:","5:","1[3[7[9:","0:"},{"2[9[5[6:","parr:","1[0[4[7:","ast:"}},
		help1 = "mover bola",
		help2 = "poner bomba",
		help3 = "rotar camara",
		help4 = "menu en juego",
		qblast = "qblast ironball",
		program = "programacion",
		david = "david rodriguez",
		graphic = "graficos",
		elias = "elias lozano",
		music = "musica",
		jordi = "jordi gutierrez",
		microjocs = "microjocs 2003",
		web = "www]microjocs]com",
		beginTime ="tiempo",
		seconds = "segundos",
		congrats1 = "lo conseguiste_",
		congrats2 = "enhorabuena_",
		tips[][] ={{"pulsa 5 para poner","bombas y destruir","el bloque que te","impide llegar a","la salida]"},
				   {"cuidado con la bola","electrica] si te","toca te paraliza","unos instantes]"},
				   {"si recoges el item","multibomba, podras","colocar mas de una","bomba a la vez]"},
				   {"el item de potencia","aumenta el alcance","de la bomba]"},
				   {"puedes subirte al","ascensor para subir","al piso superior]"},
				   {"la bola negra te","rompe con tan solo","tocarla[ esquivala","a toda costa]"},
				   {"la trampa te hace","saltar con fuerza[","puede ser util pero","puede hacerte caer","de la plataforma]"},
				   {"usa 1[3 o 7[9 para","rotar la camara y","tener siempre una","buena perspectiva]"},
				   null,
				   {"recoge los items","de tiempo extra","y acumula mas","tiempo para los","niveles superiores]"},
				   null,
				   {"la bola iman te","atrae hacia ella","con fuerza[","intenta no estar","muy cerca]"},
				   {"el item de escudo","te hace invulnera-","ble a los enemigos]"},
				   null,
				   null,
				   null,
				   null,
				   {"puedes repetir los","primeros niveles","para mejorar el","tiempo acumulado."},
				   null,
				   null,
				   null,
				   null,
				   null,
				   null,
				   {"ultimo nivel"}
			} 
		
	;
}