package com.mygdx.mongojocs.ultranaus;

// Textos para la version en castellano de Ultranaus

public class Text {

	public static final String
	
		lap="Vuelta",
		turbo="Turbo",
		energy="Energia",
		shield="Escudo",
		rocket="Misil",
		arcade="Arcade",
		practice="Practica",
		auto_on="Acelera automatico",
		auto_off="Acelera manual",
		snd_on="Sonido activado",
		snd_off="Sonido desactivado",
		how_to_play="Control",
		credits="Creditos",
		exit="Salir",
		resume="seguir",
		abort="Abortar",
		finish="Meta",
		wiped="Eliminado",
		conti="CONTINUAR",
		any_button="Pulsa algun boton",
		type_name="Introduce tu nombre",
		new_record="Record de vuelta",
		done="Ok",
		best_times="Records",
		ultranaus="Ultranaus",
		coded_by="Programacion",
		david="David Rodriguez",
		graphics_by="Graficos",
		jordi="Jordi Palome",		
		microjocs="Microjocs 2003",
		web="www.microjocs.com",
		thanks="Gracias por jugar",
		end1="ganador",
		end2="Eres el mejor",
		end3="piloto del torneo",
		end4="de la temporada",
		controls="Control",					
		cont1="2  Acelerar",
		cont2="8  Frenar o atras",
		cont3="4  Virar izquierda",
		cont4="6  Virar derecha",
		cont5="5  Lanzar misil",
		cont6="Tambien manejo con stick",
		stats="Caracteristicas", 					
		stats1="V : Velocidad",
		stats2="H : Manejo",
		stats3="P : Combate",
		item1="Mas velocidad", 
		item2="recupera energia",
		item3="Invulnerable",
		item4="Misil disparable",	
		raceover="Resultado",
		r1="o",
		r2="o",									
		r3="o",
		r4="o",
		stage="nivel",
		bestlap="Mejor vuelta",
		loading="cargando",
		intro1="preparate para el reto",
		intro2="afina tus sentidos",
		intro3="abrochate el cinturon",
		intro4="y se el mas rapido",
		intro5="pues solo puede ganar uno"
	;
}